job1f = {"_id": 1,
         "name": 1,
         "description": 1,
         "date_start": 1,
         "date_end": 1,
         "regions": 1,
         "data": 1,
         "group": 1,
         "username": 1,
         "attribution_factor": 1,
         "indicatorType": 1,
         "isDrilldownEnabled": 1,
         "isDrilldownEnabled": 1,
         }
